### ISSUE TITLE
Knell missing bonus flat status chance from headshot buff

### ISSUE THREAD

**Issue by ProfHugo** [pa001024/riven-mirror#11]
**Describe the bug**
Knell get an additional flat 20% status chance per stack of Death Knell (headshot buff, up to 3 stacks or +60% flat status) in addition to bonus crit damage. The tab for Knell doesn't account for that.

**To Reproduce**
Go to the tab for Knell.

**Screenshots**
![image](https://user-images.githubusercontent.com/23370942/55609310-31afd180-5735-11e9-95d2-848ecf1feb03.png)

Source from Wiki:
![image](https://user-images.githubusercontent.com/23370942/55609449-8eab8780-5735-11e9-9c5b-678a70f37bd2.png)

**Comment by pa001024** [comment]
Great, I ignored this before.
