### ISSUE TITLE
Weapons with multiple modes using incorrect stats.

### ISSUE THREAD

**Issue by ProfHugo** [pa001024/riven-mirror#14]
**Describe the bug**
Most weapons with multiple modes or alt-fire (Stradavar (Prime), Tiberon Prime, Zenith, Tenora, Zarr, and Pandero) are using the incorrect stats for their default fire modes. 

Stradavar Prime:
The default mode (https://riven.im/weapon/Stradavar_Prime) are using the stats for its semi-auto mode, when it should be using stats from full-auto mode (there is already a seperate entry for semi-auto mode).

Tiberon Prime:
The default mode (https://riven.im/weapon/Tiberon_Prime) are using stats for its full-auto mode, when it should be using stats from burst mode (there is already a seperate entry for semi-auto and full-auto mode) (also full-auto is misspelled as sull-auto lol).

Zenith:
The default mode (https://riven.im/weapon/Zenith) are using the stats for its semi-auto mode, when it should be using stats from full-auto mode (there is already a seperate entry for semi-auto mode).

Tenora:
The default mode (https://riven.im/weapon/Tenora) are using the stats for its charged mode, when it should be using stats from full-auto mode (there is already a seperate entry for charged mode).

Zarr:
The shotgun mode (https://riven.im/weapon/Tenora) are using the stats for its cannon mode (mislabeled as shotgun mode), when it should be using stats from shotgun mode (the one with IPS). The default mode is correctly using stats from cannon mode here, even though it mislabels it as shotgun mode.

Pandero:
The default mode (https://riven.im/weapon/Pandero) are using the stats for its burst mode, when it should be using stats from semi-auto mode (there is already a seperate entry for burst mode).

**To Reproduce**
Go to the tabs mentioned above.

**Comment by pa001024** [comment]
Really a big problem. Thanks for report.
