### ISSUE TITLE
显赫武器 武器配装 的 分享链接 无法使用

### ISSUE THREAD

**Issue by knightofbatons** [pa001024/riven-mirror#16]
**描述**
显赫武器 例如 [Valkyr之爪] [监察者双枪] 的武器配装功能 并不能通过分享链接重现 MOD 配置

**重现**
1. 在武器配装功能选中一个显赫武器进行 MOD 配置 例如 [监察者双枪]
2. 复制分享链接 打开新标签页使用 / 简单的刷新页面
3. 出现错误 MOD 配置不能重现 / MOD 配置消失

**预期的行为**
正常情况下 MOD 配置应该可以通过分享连接正确重现

**桌面端：**
 - 操作系统: Win10
 - 浏览器 Chrome
 - 版本 73.0.3683.103（正式版本） （64 位）

**Comment by knightofbatons** [comment]
感觉和 URL 加成 部分的参数有关 因为普通武器在录入 加成 以后的连接也无法重现 MOD 配置 而 显赫武器的配装页面会自带一个技能强度的加成项

**Comment by pa001024** [comment]
感谢反馈^_^  已经正常了
