### ISSUE TITLE
Suggestion: Keep manual data entry for riven editor (and remove min/max value caps)

### ISSUE THREAD

**Issue by ProfHugo** [pa001024/riven-mirror#18]
By keeping (uncapped) manual data entry users can test legit builds post nerf after a dispo update between the time the update drops and the site being updated with new dispo. 

It's also faster to type in the numbers directly versus sliding a slider, but that's just me.

Most importantly, it allows us to play with meme stats and see how ridiculus it can get. It's fun to see how an MK1 Braton does with +60000% dmg and +80000% crit chance :P.

**Comment by pa001024** [comment]
This change is mainly to improve input efficiency.
The limit now is canceled when using the old manual input form (you can enable it in Setting page).

**Comment by pa001024** [comment]
![image](https://user-images.githubusercontent.com/1817876/55934047-fac04b00-5c61-11e9-8365-53e8979fb40a.png)

**Comment by ProfHugo** [comment]
Genius.
