### ISSUE TITLE
惡狼戰錘的裂罅傾向性為0.96 極鏡裡的裂罅傾向性顯示為1 拉高了紫卡平均數值 麻煩修正

### ISSUE THREAD

**Issue by His6125** [pa001024/riven-mirror#19]
**描述错误**
对bug的清晰简洁描述。

**重现**
重现行为的步骤：
1. 使用某功能或某页面
2. 点击某按钮或调整某数值
3. 出现错误

**预期的行为**
清楚简洁地描述您期望发生的事情。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**桌面端（请填写以下信息）：**
 - 操作系统: [如 Win10, OSX等]
 - 浏览器 [如 Chrome, 搜狗浏览器等]
 - 版本 [如 1.14.15]

**智能手机（请填写以下信息）：**
 - 设备: [如 iPhone6]
 - 操作系统: [如 iOS8.1]
 - 浏览器 [如 Chrome, Safari]
 - 版本 [如 1.14.15]

**附加内容**
在此添加有关此问题的任何其他内容。

**Comment by pa001024** [comment]
好的
