### ISSUE TITLE
Gas damage calculator not showing dps of DoT effect, only the initial burst on hit.

### ISSUE THREAD

**Issue by ProfHugo** [pa001024/riven-mirror#20]
**Describe the bug**
In the status calc tab, it does not show the DPS values for the toxin DoT for gas, only the damage it does when the effect procs initially (simulacrum appears to still account for the toxin DoT).

**To Reproduce**
Build any weapon for gas, then go to status calc tab.

**Screenshots**
Example: Secura Penta built for gas
Build and status calc:
![image](https://user-images.githubusercontent.com/23370942/56014566-a68d8900-5caa-11e9-8f0f-a9a7606fe6f4.png)
Shown Proc DPS: 376.36

Simulacrum (VS robotic enemy):
![image](https://user-images.githubusercontent.com/23370942/56014625-e81e3400-5caa-11e9-9ee9-14d641fc78fe.png)
Actual Proc DPS: 2551-2835

**Comment by pa001024** [comment]
Ok, Gas duration is truely 0s, but when calculate DoT damage it should be same as Toxin's 8s.
And to solve this problem, all Gas will be replace by Toxin in the Stats calc.
