### ISSUE TITLE
Lacking behaviour in Weapon Builder

### ISSUE THREAD

**Issue by JariWeis** [pa001024/riven-mirror#21]
**Describe the bug**
When using the Weapon Builder, if you set your Headshot Rate to 100%, and then add Harrow's Covenant to the list of buffs, it will take the 50% Crit Chance buff for bodyshots, instead of the 200% Crit Chance for headshots.

**To Reproduce**
1. Go to Weapon Builder.
2. Click on a weapon.
3. Scroll down to "Headshot Rate"
4. Drag the slider to 100%.
5. Slot the mods you want to use.
6. Select "Harrow Covenant Buff".
7. Scroll down to the "Minimap" display.
8. See that the Rubico has only 50% Crit Chance on top of its modded Crit Chance of 95%, instead of the 200% it is supposed to have.

**Expected behavior**
At step 8. it should have ( 95 + 200 = ) 295% Crit Chance, instead of ( 95 + 50 = ) 145% Crit Chance.

**Screenshots**
I have attached a screenshot.
![Screenshot_21](https://user-images.githubusercontent.com/49565841/56050737-f2910a00-5d4c-11e9-9c0c-49b1eeae4ed7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Browser Vivaldi (64-bit)
 - Version 2.4.1488.38

**Comment by pa001024** [comment]
fixed

**Comment by JariWeis** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/49565841/56056384-54a53b80-5d5c-11e9-8213-b1ac607b5944.png)
It has been fixed! Thank you very much for the quick response!
