### ISSUE TITLE
Gas DPS not calculated correctly

### ISSUE THREAD

**Issue by ProfHugo** [pa001024/riven-mirror#22]
**Describe the bug**
Kind of a continuation of #20. Simply copying the formula from toxin to gas is incorrect. 

Toxin proc's damaging effect only consist of a DoT, which does base damage * (toxin mod multi / 2) per tick for 9 ticks over 8 seconds.

Gas, however, does the following: when the effect procs, it immediately does toxin damage equal to base damage * (toxin mod multi / 2) to everything in a 3m radius, then applies a DoT effect to all enemies hit (similar to toxin, but a bit different), which does base damage * (toxin mod multi / 2)^2 per tick for 9 ticks over 8 seconds (the toxin portion of the DoT is squared). 

In addition, while DoTs like slash and toxin procs gets double dipped (1.55^2 with a maxed primed bane mod) with faction mods (this appears to work correctly in the builder), gas proc gets affected like this: the 3m initial burst gets double dipped, and the DoT gets triple dipped (1.55^3 with a maxed primed bane mod).

To fix this, the initial burst of damage needs to be added to the net proc DPS, the toxin portion of the DoT formula needs to be squared, and if there is a faction mod, the burst needs to account for the double dip, and the DoT needs to account for the triple dip. 

Wikia links:
https://warframe.fandom.com/wiki/Damage/Toxin_Damage
https://warframe.fandom.com/wiki/Damage/Gas_Damage

**Comment by pa001024** [comment]
it's a typo in https://github.com/pa001024/riven-mirror/blob/5c264a954cd7f590420c1de89aa38575a2899664/src/warframe/modbuild.ts#L720
should be gasBaseDamage.

**Comment by pa001024** [comment]
now it should be correctly

**Comment by ProfHugo** [comment]
Gas dps is still calculated incorrectly. Generally, with the same toxin multiplier, gas should do more significantly more damage than toxin, since toxin only applies a DoT everytime it procs, while gas not only applies a stronger DoT if enough toxin mods are stacked (base damage * (toxin mod multi / 2)^2 is greater than base damage * (toxin mod multi / 2) when the toxin multiplier is greater 2), but there's also the additional burst of damage gas applies when it procs. However, it is clearly not the case for pretty much all weapons I've tested the builder with.

**Example: Boltor Prime** (Crit chance and IPS removed, fire rate reduced to 1 round per sec, and status chance increased to 100% for simplicity sake; the targeted status effect will proc exactly once per second)

 - Test Case 1a: With only +90 toxin (toxin proc):
![image](https://user-images.githubusercontent.com/23370942/56090764-615c8900-5e5b-11e9-9ab3-76dd8f5e66e4.png)

   - Expected Result:
      - Instant Proc Damage per Hit/Second: 46 * (1.9 / 2) = 43.7 dmg
      - Latent Proc DPS: 43.7 * 9 = 393.3 dps
   - Actual Result:
      - 48.94 dmg per hit/tick (slightly off from expected value)
      - 440.5 latent proc dps (which is 48.94 * 9)

 - Test Case 1b: With +90 toxin + 90 heat (gas proc):
![image](https://user-images.githubusercontent.com/23370942/56090871-99180080-5e5c-11e9-870e-0b1651739550.png)

   - Expected Result (initial burst + DoT damage per tick):
      - Instant Proc Damage per Hit/Second: 46 * (1.9 / 2) + (46 * (1.9 / 2)^2) = 85.215 dmg
      - Latent Proc DPS: 85.215 * 9 = 766.935 dps
   - Actual Result:
      - 48.94 dmg per hit/tick (It should not be the same as toxin, but it is)
      - 209.24 latent proc dps (???)
  
 - Test Case 2a: With only +150 toxin (toxin proc):
![image](https://user-images.githubusercontent.com/23370942/56091066-e7c69a00-5e5e-11e9-9d3d-d45d6f6db62a.png)

   - Expected Result:
      - Instant Proc Damage per Hit/Second: 46 * (2.5 / 2) = 57.5 dmg
      - Latent Proc DPS: 57.5 * 9 = 517.5 dps
   - Actual Result:
      - 64.4 dmg per hit/tick (what's going on?)
      - 579.6 latent proc dps (which is 64.4 * 9)

 - With +150 toxin + 90 heat (gas proc):
![image](https://user-images.githubusercontent.com/23370942/56091149-db8f0c80-5e5f-11e9-8e61-b56f7ad8df25.png)

   - Expected Result (initial burst + DoT damage per tick):
      - Instant Proc Damage per Hit/Second: 46 * (2.5 / 2) + (46 * (2.5 / 2)^2) = 129.375 dmg
      - Latent Proc DPS: 85.215 * 9 = 1164.375 dps
   - Actual Result:
      - 64.4 dmg per hit/tick (same as above; should not be the same as toxin)
      - 348.32 latent proc dps (uhh...)
  
**Conclusion:**Something is terribly off about the gas calculation (and the toxin proc calc isn't very accurate either), because a gas proc should not do less damage than a toxin proc with the same toxin multiplier.

**Comment by ProfHugo** [comment]
Possible location of error: the function gasBaseDamage() is returning the wrong value.
```
get gasBaseDamage() {
    return hAccMul(this.baseDamage, (1 + this.toxinMul) ** 2 / 2);
}
```
The formula is baseDmg * (1 + toxMulti / 2)^2, while this function returns baseDmg * ((1 + toxMulti)^2 / 2), which, well, results in incorrect DPS values. In math, terms cannot be squared in different order, and this applies here aswell. In this gase, the correct function should be
```
get gasBaseDamage() {
    return hAccMul(this.baseDamage, (1 + this.toxinMul / 2) ** 2);
}
```

**Comment by pa001024** [comment]
> * Expected Result:
>   
>   * Instant Proc Damage per Hit/Second: 46 * (1.9 / 2) = 43.7 dmg
>   * Latent Proc DPS: 43.7 * 9 = 393.3 dps
> * Actual Result:
>   
>   * 48.94 dmg per hit/tick (slightly off from expected value)
>   * 440.5 latent proc dps (which is 48.94 * 9)

![image](https://user-images.githubusercontent.com/1817876/56096266-a1ce0c80-5f18-11e9-8e3e-8b0b0223ad08.png)

DoT is affect by crit multiplier. so you need remove crit chance btw

**Comment by pa001024** [comment]
This part has been rewrite.
should be ok right now.

**Comment by ProfHugo** [comment]
Ok the DoT part of the gas proc seems to be calculated correctly now. However, right now 
- It still doesn't account for the damage on proc, which does moddedBaseDmg * (toxMulti / 2) * factionMod, and should adds that much damage * fire rate * proc probability to the average proc DPS. Currently it displays the dps of the DoT only.

Same Boltor (stripped away cc this time):
- 90 Toxin (toxin)
![image](https://user-images.githubusercontent.com/23370942/56099544-47ef2780-5ec3-11e9-9e88-b356f27c81af.png)
   - Calculated correctly

- 90 Toxin + 90 Heat (gas)
![image](https://user-images.githubusercontent.com/23370942/56099560-7d941080-5ec3-11e9-9a49-07bf7c4877a7.png)
   - Expected Result:
      - Instant Proc per Hit/sec: Initial + DoT = 46 * (1.9 / 2) + (46 * (1.9 / 2)^2) = 43.7 + 41.515 = 85.215 
      - Latent proc DPS: Initial + DoT * maxProcStack = 46 * (1.9 / 2) + (46 * (1.9 / 2)^2) * 9 = 417.335 dps
   - Actual Result:
      - 43.7 (only the initial part)
      - 373.63 latent dps (which turns out to be approx. 41.515*9, only the DoT part)

 - The DoT of gas should be triple dipped with faction mods, but right now it's only double dipped.

**Comment by pa001024** [comment]
I don't think it has twice DoT damage at one time. (like 46 * (1.9 / 2) + (46 * (1.9 / 2)^2) )

> * Instant Proc per Hit/sec: Initial + DoT = 46 * (1.9 / 2) + (46 * (1.9 / 2)^2) = 43.7 + 41.515 = 85.215
> * Latent proc DPS: Initial + DoT * maxProcStack = 43.7 + 41.515 * 9 = 417.335 dps

just as follow : 
Instant Proc per Hit/sec: 46 * (1.9 / 2)
Latent proc DPS: Initial + DoT * (maxProcStack-1)

**Comment by pa001024** [comment]
> * The DoT of gas should be triple dipped with faction mods, but right now it's only double dipped.

nop, Instant is double.

**Comment by ProfHugo** [comment]
> I don't think it has twice DoT damage at one time. (like 46 * (1.9 / 2) + (46 * (1.9 / 2)^2) )
> 
> > * Instant Proc per Hit/sec: Initial + DoT = 46 * (1.9 / 2) + (46 * (1.9 / 2)^2) = 43.7 + 41.515 = 85.215
> > * Latent proc DPS: Initial + DoT * maxProcStack = 43.7 + 41.515 * 9 = 417.335 dps
> 
> just as follow :
> Instant Proc per Hit/sec: 46 * (1.9 / 2)
> Latent proc DPS: Initial + DoT * (maxProcStack-1)
When gas procs, it does do one tick of its DoT (damage over time) at the same time as the clod does its instant burst of damage.

Here I used a Prisma Grinlok modded with only 2x 60/60 for gas and 90% toxin mod against an ancient disrupter.
![image](https://user-images.githubusercontent.com/23370942/56108077-9b329b80-5efe-11e9-99d0-c290222534b5.png)
When the bullet (598 dmg) procs gas , it spawns the toxin cloud which dealt 118 toxin damage and procs the toxin DoT, which dealt 146 damage the second it procs, then 146 damage 8 more times over the next 9 seconds. All three damage instance: the damage the bullet deals, the toxin cloud, and the first tick of the DoT, happens at the same time, when the bullet procs gas.




> > * The DoT of gas should be triple dipped with faction mods, but right now it's only double dipped.
> 
> nop, Instant is double.

The burst of damage the toxin cloud does is double dipped. (1.55^2 with primed bane), and the toxin proc DoT is triple dipped (1.55^3 with primed bane). The wiki demostrates this with their damage calc example. 

Here's the exact same test case as the one above, except I added bane of infested in addition to the other mods (don't have primed bane of infested)
![image](https://user-images.githubusercontent.com/23370942/56108531-417fa080-5f01-11e9-921b-c43f2db0923c.png)
Here the bullet does 778 damage (approx. 598 * 1.3), which spawns a toxin cloud that deals 199 toxin damage (approx. 118 * 1.3 *1.3) and proccing toxin, and the first tick of that toxin proc (which happens at the same time as the other 2), deals 322 toxin damage (approx. 146 * 1.3 * 1.3 * 1.3) damage, then 322 damage 8 more times over the next 9 seconds.

**Comment by pa001024** [comment]
![image](https://user-images.githubusercontent.com/1817876/56128194-8fec7800-5fb1-11e9-8496-f58fd8f0a3c7.png)

![image](https://user-images.githubusercontent.com/1817876/56128181-895e0080-5fb1-11e9-9a75-ff62db7f0e04.png)

about 8 times

**Comment by ProfHugo** [comment]
Actually, why not just seperate and create a new section for the gas's toxin DoT. Instead of combining it under "Gas," have "Gas (Cloud Burst Damage)" which only has the DPS values for the cloud, and "Gas (Toxin DoT)," which contains the DPS values of the DoT (what "Gas" has now).

**Comment by ProfHugo** [comment]
Right now the only issue left (I think) is that the instant burst of damage that gas does when it proc is not accounted for. It seems like the status calc is displaying the toxin DoT portion of the gas proc correctly.

**Comment by pa001024** [comment]
> Actually, why not just seperate and create a new section for the gas's toxin DoT. Instead of combining it under "Gas," have "Gas (Cloud Burst Damage)" which only has the DPS values for the cloud, and "Gas (Toxin DoT)," which contains the DPS values of the DoT (what "Gas" has now). Both would share the same proc % chance per hit and such, but calculates their DPS values seperately.

maybe a good idea
