### ISSUE TITLE
紫卡分析器无法打开

### ISSUE THREAD

**Issue by ceasry** [pa001024/riven-mirror#26]
**描述错误**
对bug的清晰简洁描述。
字面意思，无法打开紫卡分析器，打开页面是空白

代码如下
<main class="main-container">
   p.s 这里应该是有紫卡分析器的代码，但是我用的这个360极速浏览器没有
  <div class="el-dialog__wrapper update-dialog" style="display: none;">
    <div role="dialog" aria-modal="true" aria-label="更新信息" class="el-dialog" style="margin-top: 15vh;">
      <div class="el-dialog__header">
        <span class="el-dialog__title">更新信息</span>
        <button type="button" aria-label="Close" class="el-dialog__headerbtn">
          <i class="el-dialog__close el-icon el-icon-close"></i>
        </button>
      </div>
      
      <div class="el-dialog__footer"><span class="dialog-footer"><button type="button" class="el-button el-button--primary el-button--small"><span>我知道了</span></button></span></div>
      </div></div></main>

**Comment by ceasry** [comment]
> **描述错误**
> 对bug的清晰简洁描述。
> 字面意思，无法打开紫卡分析器，打开页面是空白
> 
> 代码如下
> 
> p.s 这里应该是有紫卡分析器的代码，但是我用的这个360极速浏览器没有
> 更新信息
> 我知道了

- 

- [ ] 1.

**Comment by pa001024** [comment]
？？？

**Comment by ceasry** [comment]
我重装了我的浏览器之后，问题解决了。。。



------------------ 原始邮件 ------------------
发件人: "pa001024"<notifications@github.com>; 
发送时间: 2019年4月26日(星期五) 晚上6:00
收件人: "pa001024/riven-mirror"<riven-mirror@noreply.github.com>; 
抄送: "ceasry"<qiufeng096@163.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [pa001024/riven-mirror] 紫卡分析器无法打开 (#26)




？？？
