### ISSUE TITLE
Wrong Damage Type for Gas Proc DoT

### ISSUE THREAD

**Issue by ProfHugo** [pa001024/riven-mirror#27]
The gas proc DoT does toxin damage per second, not gas damage (only the initial burst is gas damage, the DoT is toxin).

When the "Damage Model" is changed to grineer cloned flesh, the gas proc dps should not change (since toxin is neutral against cloned flesh), but instead it's decreased by 50% (gas damage has a 50% penalty against cloned flesh, not toxin).

**Comment by pa001024** [comment]
Roughly tested
