### ISSUE TITLE
可不可以加入同伴和archwing的mod配装？和战甲配装一样的那种

### ISSUE THREAD

**Issue by jameszd44** [pa001024/riven-mirror#30]
**您的功能请求是否与问题有关？ 请描述一下。**
简明扼要地描述了问题所在。比如：我觉得某功能不合适

**描述你想要的解决方案**
简明扼要地描述您想要发生的事情。

**描述您考虑过的替代方案**
对您考虑的任何替代解决方案或功能的简明扼要描述。

**附加内容**
在此处添加有关功能请求的任何其他内容或屏幕截图。

**Comment by pa001024** [comment]
fixed by 556b16c4a2344b14ce92c0b754bf5c2f2bfb6a0e
