### ISSUE TITLE
建议添加语言链接入口

### ISSUE THREAD

**Issue by XXFT** [pa001024/riven-mirror#31]
在域名后面添加参数，能设置当前进入界面的语言。
比如：采用 riven.im/riven?language=ZHCN 可以进入国服语言界面

**Comment by pa001024** [comment]
问一下具体有啥用途么

**Comment by XXFT** [comment]
没什么用途，如果你觉得麻烦就当我没问过好了

**Comment by pa001024** [comment]
加了 格式是 lang=en|zh-CN|zh-TW|zh-CY

**Comment by XXFT** [comment]
好的 感谢
