### ISSUE TITLE
无法上传紫卡截图

### ISSUE THREAD

**Issue by LJason77** [pa001024/riven-mirror#4]
**描述错误**
**紫卡分析**无法上传紫卡截图

**重现**
重现行为的步骤：
1. 紫卡分析
2. 将图片拖到对应框（或者点击**上传截图**上传）
3. 无任何反应

**预期的行为**
对上传的紫卡截图进行分析。

**桌面端（请填写以下信息）：**
 - 操作系统: Win10
 - 浏览器：Chrome
 - 版本：73.0.3683.86 64位

**Comment by pa001024** [comment]
无法重现 可能是网络问题

**Comment by LJason77** [comment]
![批注 2019-03-31 230329](https://user-images.githubusercontent.com/11374869/55290719-3c9ef500-5409-11e9-845f-f9d8c39ba466.png)
点击上传之后，是出现这个错误：
**net::ERR_CERT_COMMON_NAME_INVALID**

**Comment by pa001024** [comment]
证书错误。。。先自行搜索解决一下
清除浏览器缓存
chrome://net-internals/#hsts
dns劫持
代理设置问题
等等

**Comment by LJason77** [comment]
![批注 2019-04-02 022947](https://user-images.githubusercontent.com/11374869/55350679-36834400-54ef-11e9-8be3-e662edd26c09.png)
我觉得可能是证书错了，**api.0-0.at** 的证书是颁发给 **api.riven.im** 的。不止我一人有这个问题，我认识的人全都上传不了截图。

这个问题出现好久了，清除缓存、DNS劫持、代理等等我们也都排除了。

**Comment by pa001024** [comment]
我知道了 因为我一直用的剪贴板接口没注意到
文件上传这块的域名错了 应该是 api.riven.im 已经修正 感谢反馈
