### ISSUE TITLE
dev和build都跑不起来，有文件缺失

### ISSUE THREAD

**Issue by endday** [pa001024/riven-mirror#43]
**描述错误**
npm run dev

This dependency was not found:

* @/data/weapons.data in ./src/warframe/codex/weapon.ts

dev和build 都缺这个文件，是不是有东西没提交

**重现**

**预期的行为**
清楚简洁地描述您期望发生的事情。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

**桌面端（请填写以下信息）：**
 - 操作系统: [如 Win10, OSX等]
 - 浏览器 [如 Chrome, 搜狗浏览器等]
 - 版本 [如 1.14.15]

**智能手机（请填写以下信息）：**
 - 设备: [如 iPhone6]
 - 操作系统: [如 iOS8.1]
 - 浏览器 [如 Chrome, Safari]
 - 版本 [如 1.14.15]

**附加内容**
在此添加有关此问题的任何其他内容。

**Comment by pa001024** [comment]
see https://github.com/pa001024/riven-mirror-data
