### ISSUE TITLE
Mesa Regulators classified as Melee/Unable to use simulacrum

### ISSUE THREAD

**Issue by Xuerian** [pa001024/riven-mirror#5]
**Describe the bug**
Mesa Regulators classified as Melee/Unable to use simulacrum

**To Reproduce**
Select Regulators in weapon builder
Click Sim tab

**Expected behavior**
Able to use simulacrum

**Desktop (please complete the following information):**
 - OS: W10
 - Browser FF
 - Version 67

**Comment by pa001024** [comment]
fixed
