### ISSUE TITLE
Direct links not working

### ISSUE THREAD

**Issue by ProfHugo** [pa001024/riven-mirror#66]
Any direct links that isn't to riven.im's homepage (ex: https://riven.im/weapon/Simulor or https://riven.im/palette) returns a DNS_PROBE_FINISHED_NXDOMAIN on Chrome and can;t be accessed. On Edge it's INET_E_RESOURCE_NOT_FOUND. 

You can still navigate to where that link points to starting from the homepage, but when you refresh the webpage or tries to click on a non homepage link, it doesn't load the webpage.

My DNS server is 8.8.8.8 (Google). However users using other DNS servers are also seeing the same thing.

**Comment by pa001024** [comment]
Should be resolved
