### ISSUE TITLE
Volt abilities tab for speed/shield broken

### ISSUE THREAD

**Issue by Xuerian** [pa001024/riven-mirror#7]
**Describe the bug**
Buff values mangled/uncalculated

**To Reproduce**
Go to Volt (prime) builder abilities tabs

**Comment by pa001024** [comment]
Shield is NOT affected by power strength. so its not a bug.
...and Speed works correctly.
So I don't know what you mean.

**Comment by Xuerian** [comment]
Maybe it's an FF bug. 
https://i.imgur.com/b4doY89.png
https://i.imgur.com/sOYS1qg.png

**Comment by pa001024** [comment]
ok, its a multi-language bug. I will fix it.
And you can go to "Setting" and click "English" to fix this problem in the meanwhile.
