### ISSUE TITLE
武器配装中，切换配置后，伤害模型的显示和实际值会出现不一致的情况

### ISSUE THREAD

**Issue by TWT233** [pa001024/riven-mirror#71]
**描述错误**
武器配装中，切换配置后，伤害模型的显示和实际值会出现不一致的情况

**重现**
**预期的行为**
**截图**
![image](https://user-images.githubusercontent.com/11287700/75237892-1f320100-57fb-11ea-9fbe-e7cf260f11d0.png)
 如图 我配了一套A配置，然后选好了伤害模型，在触发计算中计算出的伤害是这个值
之后我切换到B配置，此时可以看到伤害模型没有切换，我配置了同样一套MOD，但触发计算中计算出的伤害与A配置不同，所以I骑士是没有生效的，这个时候调整一下伤害模型就可以了，伤害模型显示的效果和实际值出现了不一致。
![image](https://user-images.githubusercontent.com/11287700/75237962-3ffa5680-57fb-11ea-8d9c-ae5ccf4710e5.png)

**桌面端（请填写以下信息）：**
chrome

**Comment by pa001024** [comment]
感谢
